# Generated by Django 5.1.3 on 2024-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrenamiento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "descripcion",
                    models.TextField(null=True, verbose_name="Descripción"),
                ),
                (
                    "ejercicios",
                    models.TextField(max_length=500, verbose_name="Ejercicios"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        null=True,
                        upload_to="imagenes_entrenamiento/",
                        verbose_name="Imagen",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
