# Generated by Django 5.1.3 on 2024-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FitGym", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(null=True, verbose_name="Descripción"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        null=True,
                        upload_to="imagenes_ejercicio/",
                        verbose_name="Imagen",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="entrenamiento",
            name="ejercicios",
        ),
        migrations.AddField(
            model_name="entrenamiento",
            name="ejercicios",
            field=models.ManyToManyField(
                related_name="entrenamientos",
                to="FitGym.ejercicio",
                verbose_name="Ejercicios",
            ),
        ),
    ]
