# Generated by Django 5.1.3 on 2024-11-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FitGym", "0002_ejercicio_remove_entrenamiento_ejercicios_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrenamiento",
            name="imagen",
            field=models.ImageField(
                default="", upload_to="imagenes_entrenamiento/", verbose_name="Imagen"
            ),
        ),
    ]
