# Generated by Django 5.1.3 on 2024-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FitGym", "0003_alter_entrenamiento_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrenamiento",
            name="imagen",
            field=models.ImageField(
                upload_to="imagenes_entrenamiento/", verbose_name="Imagen"
            ),
        ),
    ]
